online-mode=false
enforce-secure-profile=false
level-type=minecraft\:flat
level-seed=blueprint
generate-structures=false
gamemode=survival
difficulty=peaceful
spawn-protection=0
allow-flight=true
view-distance=8
simulation-distance=6
max-players=10
motd=Blueprint test server
enable-command-block=false
sync-chunk-writes=false
